name: curve_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  percent_indicator: ^4.0.1
  cupertino_icons: ^1.0.2
  get: any
  smooth_page_indicator: 1.1.0
  connectivity_plus: 4.0.2
  country_code_picker: 3.0.0
  csc_picker: 0.2.7
  dio: 5.3.3
  shared_preferences: 2.2.1
  intl_phone_field: 3.2.0
  flutter_svg: ^2.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Tajawal
      fonts: 
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: TajawalM
      fonts: 
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: TajawalR
      fonts: 
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: TajawalL
      fonts: 
        - asset: assets/fonts/Tajawal-Light.ttf
  uses-material-design: true

